using System.Reflection;

namespace BizHawk.Emulation.Cores.Nintendo.NES
{
    /// <summary>
    /// Provides compile-time enumeration of all types in this assembly.
    /// This is normally generated by BizHawk.SrcGen.ReflectionCache but is
    /// provided here as a manual fallback since the source generator requires
    /// a specific build environment.
    /// </summary>
    public static class ReflectionCache
    {
        public static readonly Type[] Types = typeof(ReflectionCache).Assembly.GetTypes();
    }
}
